name: CI  # Continuous Integration（継続的インテグレーション）ワークフロー名

# main・developブランチへのpushやプルリクエストが対象
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest  # Ubuntuの最新環境で実行

    steps:
      # リポジトリのコードをチェックアウト（取得）
      - uses: actions/checkout@v3

      # Node.jsのセットアップ（バージョン18を指定）
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 依存パッケージをインストール
      - run: npm install

      # ESLintでコードの静的解析（lint）を実行
      - run: npm run lint

      # テストを実行（package.jsonのtestスクリプトを実行）
      - run: npm test
