name: CI  # Continuous Integration（継続的インテグレーション）ワークフロー名

on:
  push:
    branches:
      - main   # mainブランチへのpushがトリガー
      - develop  # developブランチへのpushもトリガー
  pull_request:  # 全てのプルリクエストがトリガー

jobs:
  test-and-lint:
    runs-on: ubuntu-latest  # 最新のUbuntu環境で実行

    steps:
      # リポジトリのコードをチェックアウト（取得）
      - uses: actions/checkout@v3

      # Node.jsのセットアップ（バージョン18を指定）
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # npmパッケージの依存関係をインストール
      - run: npm install

      # ESLintを実行し、コードの静的解析（lint）を行う
      - run: npm run lint

      # Jestでテストを実行
      # ts-nodeを使ってTypeScript製のjest.config.tsを読み込めるように環境変数をセット
      - name: Run tests
        run: npm test
        env:
          NODE_OPTIONS: "--loader ts-node/esm"  # ts-nodeのESMローダーを有効化
