name: CI  # Continuous Integration（継続的インテグレーション）ワークフロー名

# トリガー設定：main, developへのpush、すべてのPRで発火
on:
  push:
    branches:
      - main     # mainブランチへのpush
      - develop  # developブランチへのpush
  pull_request:  # すべてのPR

jobs:
  test-and-lint:
    runs-on: ubuntu-latest  # 最新のUbuntu環境で実行

    steps:
      # リポジトリのソースコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.js v18をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # npm依存関係のインストール
      - name: Install dependencies
        run: npm install
        working-directory: .  # プロジェクトルートで実行

      # ESLintで静的コード解析を実行
      - name: Run ESLint
        run: npm run lint
        working-directory: .

      # Jestでテストを実行
      # ts-node/esmを使ってTypeScriptのJest設定を読み込めるようにする
      - name: Run tests
        run: npm test
        env:
          NODE_OPTIONS: "--loader ts-node/esm"
